version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: ./postgres/.env.local

  hasura:
    image: hasura/graphql-engine:v1.3.2
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    env_file: ./hasura/.env.local

  ads:
    build:
      context: ./ads
    ports:
      - 3000:3000
    volumes:
      - ./ads:/app
    env_file: ./ads/.env.local

  news:
    build:
      context: ./news
    ports:
      - 3001:3000
    volumes:
      - ./news:/app
    env_file: ./news/.env.local
volumes:
  db_data:
